### ISSUE TITLE
2022 Camp Listing

### ISSUE THREAD

**Issue by dfleck** [burningmantech/Burning-Man-Innovators#6]
**Is your feature request related to a problem? Please describe.**
It looks like camps that are part of a village aren't included in the camp listings - on the web at https://burningman.org/event/2022-camp-listing/ or thru the api.

**Describe the solution you'd like**
Include camps that are part of a village.

**Comment by lostways** [comment]
@dfleck Is this the case now?

**Comment by dfleck** [comment]
No. All is well now.
